### ISSUE TITLE
Viewing the users collection via Houston?

### ISSUE THREAD

**Issue by jononomo** [gterrono/houston#123]
First of all, I see three collections if I go to the meteor mongo shell: 
    houston_admins
    system.indexes
    users

However, none of these are showing up in my Houston admin panel.  My question is -  why not, and how can I get them to?

My first attempt was to add this line to my main javascript file:

```
Houston.add_collection(users);
```

But I get an error as follows:

```
(STDERR) ReferenceError: users is not defined
```

**Comment by fidergo-stephane-gourichon** [comment]
For future readers, more complete solution with `import` line on on https://github.com/gterrono/houston/issues/372#issuecomment-265442490

```
import { Meteor } from 'meteor/meteor';
import 'meteor/houston:admin';

Houston.add_collection(Meteor.users);
Houston.add_collection(Houston._admins);
```
