### ISSUE TITLE
uncaught TypeError on meteor.users

### ISSUE THREAD

**Issue by charliemagee** [gterrono/houston#203]
Houston v 1.0.6
iron-router v 0.7.1
blaze-layout v 0.2.4
meteor v 0.8.2

This Houston error is stopping my deployed app in it's tracks. On local it shows the Houston Home screen with all collections, but when I click a collection the screen goes completely blank, including nav. When watching the HTML in Chrome devtools, the houston div simply disappears.

I placed this suggested code into my app:

Houston.add_collection(Meteor.users);
Houston.add_collection(Houston._admins);

Error in console:

(function(){Houston.add_collection(Meteor.users);
 x Uncaught TypeError: undefined is not a function
Houston.add_collection(Houston._admins);

Any clues? Is it supposed to load ahead or behind something else? Is it supposed to have a waitOn in my router code?

Thanks,

Charlie Magee

**Comment by robertclarkson** [comment]
I had this issue, and when i moved the add_collection to a server only file, it went away.

**Comment by MichaelJCole** [comment]
@robertclarkson Thanks!
