### ISSUE TITLE
package won't load under meteor 0.9.3

### ISSUE THREAD

**Issue by charliemagee** [gterrono/houston#234]
I upgraded an app to meteor 0.9.3 and it failed to run. Had to go through the app and remove/add packages one at a time. Houston is the only one that won't reinstall and I'm committed to it for my admin stuff.

Here's the error I get when trying to add it:

---

Figuring out the best package versions to use. This may take a moment.
Could not satisfy all the specified constraints:
Error: conflict: constraint blaze@1.0.0 is not satisfied by 2.0.1.
Constraints on blaze come from:
  <top level>
  mrt:houston@1.0.7 -> cmather:iron-router@0.8.2 -> cmather:iron-layout@0.2.0 -> cmather:iron-dynamic-template@0.2.1
  standard-app-packages@1.0.2 -> meteor-platform@1.1.1

---

Perhaps Atmosphere isn't grabbing the latest version?

**Comment by aj07mm** [comment]
Same prob here. i tried to do what @AlexeyMK told about git clone the repo into <project_home>/packages but it didn't worked. I tried to downgrade my meteor version to 1.0 but still not working

**Comment by aj07mm** [comment]
I downgraded to Meteor 1, and now its working fine.
