### ISSUE TITLE
Infinite scrolling not working

### ISSUE THREAD

**Issue by kdanninger** [gterrono/houston#253]
I'm not 100% confident that this is the case? I upgraded recently, and just noticed it stopped working. There are no errors in my JS console.

I'll test an older version and confirm this when I can.

Specs: Meteor 1.0 & houston:admin@1.2.0

**Comment by pauldowman** [comment]
Filtering is an obvious workaround if you know what you're looking for, but right now you can't use Houston to generally browse and edit your data.

@AlexeyMK Do you have any idea where the issue might be? I might take a look depending on how big of a task it seems to be.

**Comment by AlexeyMK** [comment]
I spoke with @shanereustle earlier about the issues - essentially, there's
about a day/half-day's work in terms of getting a fix implemented. I don't
have the bandwidth in the near term, but pull requests are very welcome and
I would be happy to answer any questoins.

**Comment by niranjans** [comment]
I am having the same issue. Has anoyone got a workaround to this? Or is this not useable at the moment?

**Comment by gterrono** [comment]
Fixed by #339. Sorry it took so long. The update is on atmosphere now.
