### ISSUE TITLE
What to do if you delete admin

### ISSUE THREAD

**Issue by pld32** [gterrono/houston#275]
ok so I delete the admin, dam it, and now can not access. I tried to remove the package and re-install but still get. You are not an Admin. If you need to use the Houston Admin, please ask your Admin to grant you access. message. Is there anyone with step by step instructions on how to correct?

**Comment by AlexeyMK** [comment]
I recommend using meteor mongo to delete the Houston collection which
stores the admin user id

**Comment by mcrayne** [comment]
Not sure if this is the preferred procedure, but it works. It may be too simplistic for some. (I just tried out this package so I may be missing something - but the following works);

once your app is started, start up the mongo shell
then, see what users are in the houston_admin collection with
---
 db.houston_admins.find().pretty() 
---

The document(s) have only one field and the _id: field. You need to either add a document with the user_id set to the _id of the user you want as the admin or change the existing document by setting the user_id to the _id of the user you want to be the admin. You can find the users with:

---
db.users.find().pretty()
---

**Comment by repjackson** [comment]
And if you're the only person on a site you can just drop the table with `db.houston_admins.drop()` then go to the Houston admin page (/admin by default) and claim admin.

**Comment by HammyHavoc** [comment]
I got up to using db.houston_admins.find().pretty() and nothing shows up, it's as if the command wasn't entered.
