### ISSUE TITLE
Custom action buttons do not appear to work.

### ISSUE THREAD

**Issue by nicksergeant** [gterrono/houston#285]
I'm on `2.0.3`, and have configured a custom action as per the documentation. You can see that code [here](https://github.com/nicksergeant/fingerlakescomfort/blob/master/server/houston.js#L4-13):

```
Houston.methods('Testimonials', {
  'Publish': function(testimonial) {
    Testimonials.update(testimonial._id, { $set: { published: true }});
    return testimonial.name + ' published successfully.';
  },
  'Unpublish': function(testimonial) {
    Testimonials.update(testimonial._id, { $set: { published: false }});
    return testimonial.name + ' unpublished successfully.';
  }
});
```

The buttons, however, do not appear in the admin:

![http://i.imgur.com/DklfJfk.png](http://i.imgur.com/DklfJfk.png)

**Comment by AlexeyMK** [comment]
If I had to guess, the issue is that the code is in /server instead of in
/lib, since the actions need to also be populated on the client.

Give that a try and let me know!

**Comment by nicksergeant** [comment]
I thought that as well, but the README specifically says "On the server":

![http://i.imgur.com/eNRBluk.png](http://i.imgur.com/eNRBluk.png)

Additionally, when I place the code in `lib/`, I get a JS error in the browser:

![http://i.imgur.com/GcN2VAu.png](http://i.imgur.com/GcN2VAu.png)

**Comment by nicksergeant** [comment]
Also, placing the code in `lib` does not make the buttons appear, either.

**Comment by nicksergeant** [comment]
Found the problem by looking at the [test app's implementation](https://github.com/gterrono/houston/blob/master/test/test_app/test.js#L66-L71). The first argument to `Houston.methods` needs to be the collection object itself, not a String.

The README seems to indicate that either the actual collection object or a string representation of the collection can be used, but in my case the string does not work.

**Comment by nicksergeant** [comment]
Actually, my mistake. The string representation works if you use the proper casing for the collection name itself, not the initialization of the collection. For example:

```
Testimonials = new Mongo.Collection('testimonials');
```

Either of these Houston configurations _will_ work:

```
Houston.methods('testimonials') ...
```
```
Houston.methods(Testimonials) ...
```

But this will _not_ work:

```
Houston.methods('Testimonials') ...
```

**Comment by AlexeyMK** [comment]
TIL.  Thanks Nick!
