### ISSUE TITLE
Top heading on github project site has wrong link to atmospherejs.com!

### ISSUE THREAD

**Issue by wunderkind2k1** [gterrono/houston#305]
Hi,

you are using _https://atmospherejs.com/package/houston_ instead of __https://atmospherejs.com/houston/admin__.

The wrong link leads to the unwanted url: _https://atmospherejs.com/mrt/houston_ which is not the admin tool that is expected...

Best, Sven

**Comment by AlexeyMK** [comment]
Good call! Would you mind sending in a quick PR?

**Comment by wunderkind2k1** [comment]
Will do!
Alexey Komissarouk <notifications@github.com> schrieb am Do., 9. Juli 2015
um 18:49:

> Good call! Would you mind sending in a quick PR?
>

**Comment by wunderkind2k1** [comment]
Hey Alexey,

I just forked, edited the heading but I can't issue a pull request. Reason: No source diffs. :-)
I think the problem is that the heading is an element of the github project page.

Would you please be so kind and exchange the link on your own?

Thanks.

Sven

**Comment by gterrono** [comment]
Thanks for pointing that out! Fixed.
