### ISSUE TITLE
local host can't work?

### ISSUE THREAD

**Issue by SoilChang** [gterrono/houston#307]
2.0.3 houston.  I try to log in with my meteor account. i even reset my password to make sure it is correct. but it keeps showing  user not found.  is it becasue im doing it on localhost?

To make sure we can help you quickly, please include the version of Houston
you are using, steps to replicate the issue, a description of what you were
expecting and a screenshot if relevant.

Thanks!

**Comment by samcorcos** [comment]
Unfortunately you cannot just log in with your Meteor account without setting up accounts within your meteor project.

If you want to log in with your Meteor account, try this:
http://docs.meteor.com/#/full/meteor_loginwithexternalservice

**Comment by SoilChang** [comment]
Thanks for the reply. I have found the solution.
