### ISSUE TITLE
ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by cunneen** [gterrono/houston#325]
It looks like houston is trying to build the set of fields; the funny thing is that it was working fine before.

```
W20150910-21:11:35.366(8)? (STDERR) ReferenceError: _ is not defined
W20150910-21:11:35.367(8)? (STDERR)     at find_fields (packages/houston:admin/lib/shared.coffee:21:5)
W20150910-21:11:35.367(8)? (STDERR)     at Object.Houston._get_fields (packages/houston:admin/lib/shared.coffee:37:5)
W20150910-21:11:35.367(8)? (STDERR)     at Object.Houston._get_fields_from_collection (packages/houston:admin/lib/shared.coffee:15:11)
W20150910-21:11:35.367(8)? (STDERR)     at Object.Houston._setup_collection (packages/houston:admin/server/publications.coffee:40:20)
W20150910-21:11:35.367(8)? (STDERR)     at Object.Houston.add_collection (packages/houston:admin/server/exports.coffee:8:11)

```

I cleared out the collection it was referring to, and the error went away (temporarily). Here's the data that was in there, only 4 records and none of it interesting:

```json
[
  {
    "_id": "y9n6Rmr9cjJ5uYFut",
    "ProjectName": "Saved 1",
    "ProjectNumber": "Proj 1",
    "PersonReporting": "Mike Cunneen",
    "Date": "2015-09-10",
    "TimeFrom": "14:00",
    "TimeUntil": "16:31",
    "Tasks": [],
    "Description": "",
    "Comments": "",
    "userId": "JxGhsn2wRkvNDcjhp",
    "incomplete": false
  },
  {
    "_id": "J4vpWhPpieYNR9GnE",
    "ProjectName": "Project 4",
    "ProjectNumber": "Project Number 4",
    "PersonReporting": "Mike Cunneen",
    "Date": "2015-09-10",
    "TimeFrom": "",
    "TimeUntil": "17:36",
    "Tasks": [],
    "Description": "",
    "Comments": "",
    "userId": "JxGhsn2wRkvNDcjhp",
    "incomplete": true
  },
  {
    "_id": "wmaWy5peZcHp9xYTt",
    "ProjectName": "Hi Wendy",
    "ProjectNumber": "",
    "PersonReporting": "Mike Cunneen",
    "Date": "2015-09-10",
    "TimeFrom": "",
    "TimeUntil": "19:26",
    "Tasks": [],
    "Description": "",
    "Comments": "",
    "userId": "JxGhsn2wRkvNDcjhp",
    "incomplete": true
  },
  {
    "_id": "ccvmSwgXTiWtq2pky",
    "ProjectName": "Project 3",
    "ProjectNumber": "Project Number 3",
    "PersonReporting": "Mike Cunneen",
    "Date": "2015-09-10",
    "TimeFrom": "",
    "TimeUntil": "17:36",
    "Tasks": [],
    "Description": "",
    "Comments": "",
    "userId": "JxGhsn2wRkvNDcjhp",
    "incomplete": true
  }
]
```

If I insert that first record back in, it collapses again. Here's the code:

```
JutoCollections.MaintenanceDailyReports = new Mongo.Collection('MaintenanceDailyReports');
Ground.Collection(JutoCollections.MaintenanceDailyReports);
Houston.add_collection(JutoCollections.MaintenanceDailyReports);
```

(I tried commenting the second line, same result).

**Comment by khronedev** [comment]
Hi,

I was getting same error when i tried to use houston in package. When it's "in app" (installed in ```./.meteor/packages```) - it works fine, no errors thrown. If i create a custom package (in special meteor folder ```./packages/*```) for admin related stuff and import there this package - it throws error described in this issue. Maybe that will be helpful to fix this bug :)

**Comment by funkyremi** [comment]
I've got the same issue when trying to add the two following collections. My app is separated into different packages. 
Houston.add_collection(Meteor.users);
Houston.add_collection(Houston._admins);

**Comment by Ragsboss** [comment]
+1 even we got this problem the moment we moved Houston to a separate package..

**Comment by majochoc** [comment]
Houston is dependent on Underscore, but doesn't explicitly declare that use in its package.js file. In my project features are organized by sub packages. These packages depend on my core package which exports underscorejs. 

As other commenters have stated, if you include Houston as part of a sub package the ReferenceError crops in.

The solution is to add an explicit dependency for Houston in its package.js file for UnderscoreJS. I've forked the project and added:

  api.use('underscore@1.0.4', ['client', 'server']);

to the Meteor provided packages block (line 23 in v2.0.6) in the package.js file, and this has solved the ReferenceError for me.

**Comment by majochoc** [comment]
Made a pull request with my simple fix. #371

**Comment by gterrono** [comment]
I published the update. Let me know if there are any more issues with this.

**Comment by majochoc** [comment]
I'll test it out today, and let you know if I find anything.

**Comment by majochoc** [comment]
Works as expected. Thanks for the quick merge and update!
