### ISSUE TITLE
When I load /admin houston flashes for a second then it forward to /admin/login and shows blank screen

### ISSUE THREAD

**Issue by sferoze** [gterrono/houston#327]
I installed houston.

Then I went to /admin

The houston header flashes for a second, and then forwards me to /admin/login and just shows a blank white screen.

When I inspect the dom, I can see that everything it hidden. Underneath is the layout template for logged in users. 

What is going on, and how can I fix this?

**Comment by richardgsands** [comment]
+1 Same for me (although I'm not seeing the houston header, I just get redirected to /admin/login which is blank)

**Comment by richardgsands** [comment]
So, noticed a browser console error that "spinner" template could not be found.

Fixed problem by adding sacha spin to my project:
meteor add sacha:spin

Looks like Houston has a problem.... sorry, just couldn't resist :) But yes, need to add spin back as a dependency to the Houston project (or remove the reference to the "spinner" template).

**Comment by sferoze** [comment]
I am not getting this error. 

I am just getting a blank screen. No matter what I try. 

How come no one else has this issue. 

I am using meteor user account templates package. I wonder if that could be causing the issue.

**Comment by sferoze** [comment]
The body has a class of visibility hidden on it. Is Houston adding this?

**Comment by sferoze** [comment]
It looks like it is. But then houston templates do not render. Or they render for a split second and disappear. WHy!

**Comment by sferoze** [comment]
I figured it out. 

It was because in my Router.configure global settings, in the before handler, I was setting the layout to be the loggedOut or loggedIn layouts which was overriding Houston's layout option. 

You need to use Houston's layout for it to work. Make sure you do not override the layout.
