### ISSUE TITLE
Houston Leaks Admin Info

### ISSUE THREAD

**Issue by ksepehri** [gterrono/houston#332]
Currently Houston leaks the admin count and the admin's user_id to anyone whether they're logged in or not.

![image](https://cloud.githubusercontent.com/assets/10479194/10264351/cfd8e458-69ce-11e5-9c30-26b90719ecba.png)

**Comment by keyscores** [comment]
@ksepehri can you check if this happens when package 'insecure' is removed?

**Comment by ksepehri** [comment]
@keyscores this is without the 'insecure' package.

**Comment by keyscores** [comment]
Yeah that's pretty bad. @AlexeyMK @samcorcos have you duplicated this issue? Seems quite serious.

**Comment by almogdesign** [comment]
Any updates on this, seems best to look for a different package

**Comment by gterrono** [comment]
This was fixed by #338. The update's on atmosphere now. Thanks for letting us know.
